### ISSUE TITLE
Convert CSS into CSS Modules

### ISSUE THREAD

**Issue by sub1120** [micindia-webapp/micindia-client#64]
### Tasks
- [x] Convert all CSS into CSS Modules
- [x] Optimize CSS code
- [x] List rendering with map
- [x] De-structure props
